let pencil = document.getElementById("pencil");
let brush = document.getElementById("brush");
let eraser = document.getElementById("eraser");

pencil.onclick = function () {
    size.innerHTML = 5;
    context.lineWidth = 5;
    context.strokeStyle = "black";
    pencil.style.backgroundColor = "black";
    brush.style.backgroundColor = "white";
    eraser.style.backgroundColor = "white";
    red.style.border = "3px solid #FFFFFF";
    blue.style.border = "3px solid #FFFFFF"
    yellow.style.border = "3px solid #FFFFFF"
    orange.style.border = "3px solid #FFFFFF"
    green.style.border = "3px solid #FFFFFF"
    black.style.border = "3px solid #000000"
    purple.style.border = "3px solid #FFFFFF"
    pink.style.border = "3px solid #FFFFFF"
}
brush.onclick = function () {
    size.innerHTML = 20;
    context.lineWidth = 20;
    context.strokeStyle = "black";
    pencil.style.backgroundColor = "white";
    eraser.style.backgroundColor = "white";
    brush.style.backgroundColor = "black";
    red.style.border = "3px solid #FFFFFF";
    blue.style.border = "3px solid #FFFFFF"
    yellow.style.border = "3px solid #FFFFFF"
    orange.style.border = "3px solid #FFFFFF"
    green.style.border = "3px solid #FFFFFF"
    black.style.border = "3px solid #000000"
    purple.style.border = "3px solid #FFFFFF"
    pink.style.border = "3px solid #FFFFFF"
}
eraser.onclick = function () {
    size.innerHTML = 10;
    context.lineWidth = 10;
    context.strokeStyle = 'white';
    eraser.style.backgroundColor = "green";
    brush.style.backgroundColor = "white";
    pencil.style.backgroundColor = "black";
    red.style.border = "3px solid #FFFFFF";
    blue.style.border = "3px solid #FFFFFF"
    yellow.style.border = "3px solid #FFFFFF"
    orange.style.border = "3px solid #FFFFFF"
    green.style.border = "3px solid #FFFFFF"
    black.style.border = "3px solid #FFFFFF"
    purple.style.border = "3px solid #FFFFFF"
    pink.style.border = "3px solid #FFFFFF"
}